In [1]:
import torch


In [2]:
a=torch.tensor(2)

In [3]:
a

tensor(2)

In [4]:
b=torch.tensor([1,2,3,4])

In [5]:
c=torch.tensor([[1,2],[3,4]])

In [6]:
c

tensor([[1, 2],
        [3, 4]])

In [7]:
print(a.shape,b.shape,c.shape)

torch.Size([]) torch.Size([4]) torch.Size([2, 2])


In [8]:
a.dtype

torch.int64

In [9]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.ones((4,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
torch.randint(12,25,(4,5))

tensor([[12, 23, 22, 16, 14],
        [23, 17, 23, 20, 18],
        [24, 19, 16, 24, 15],
        [13, 16, 18, 21, 20]])

In [12]:
torch.rand((3,4))

tensor([[0.8963, 0.7449, 0.2452, 0.3592],
        [0.4467, 0.8060, 0.9214, 0.2721],
        [0.7304, 0.5268, 0.1120, 0.6845]])

In [13]:
torch.randn(3,5)

tensor([[ 1.1891,  0.7863,  1.3235, -2.4814,  0.6651],
        [-0.1782, -0.6205, -0.0351,  0.9641, -0.1484],
        [ 0.1315, -0.3716, -0.0603, -1.1080, -0.0103]])

In [14]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
import numpy as np

In [16]:
x=np.array([2,3,4])

In [24]:
x=torch.tensor(x)

In [25]:
#operations on tensor

In [26]:
x

tensor([2, 3, 4], dtype=torch.int32)

In [27]:
x*10

tensor([20, 30, 40], dtype=torch.int32)

In [28]:
y=x+10

In [29]:
y

tensor([12, 13, 14], dtype=torch.int32)

In [30]:
y.add(10)

tensor([22, 23, 24], dtype=torch.int32)

In [31]:
#reshaping tensor

In [32]:
y

tensor([12, 13, 14], dtype=torch.int32)

In [33]:
y.shape

torch.Size([3])

In [34]:
y.view(1,3)

tensor([[12, 13, 14]], dtype=torch.int32)

In [35]:
y.view(3,1)

tensor([[12],
        [13],
        [14]], dtype=torch.int32)

In [39]:
a=torch.rand(10,1)
a

tensor([[0.3500],
        [0.7187],
        [0.9827],
        [0.7864],
        [0.1899],
        [0.5691],
        [0.1119],
        [0.0441],
        [0.3860],
        [0.4032]])

In [40]:
a.view(1,10)

tensor([[0.3500, 0.7187, 0.9827, 0.7864, 0.1899, 0.5691, 0.1119, 0.0441, 0.3860,
         0.4032]])

In [41]:
torch.squeeze(a,1)

tensor([0.3500, 0.7187, 0.9827, 0.7864, 0.1899, 0.5691, 0.1119, 0.0441, 0.3860,
        0.4032])

In [42]:
assert 1==3

AssertionError: 

In [43]:
x

tensor([2, 3, 4], dtype=torch.int32)

In [44]:
x.shape

torch.Size([3])

In [45]:
x.unsqueeze(1)

tensor([[2],
        [3],
        [4]], dtype=torch.int32)

In [46]:
x=torch.randn(10,10)

In [48]:
y=x[None]
y.shape

torch.Size([1, 10, 10])

In [49]:
y2=x[:,None]

In [50]:
y2.shape

torch.Size([10, 1, 10])

In [51]:
x=torch.rand(4,5)
y=torch.rand(5,4)


In [52]:
x.matmul(y)

tensor([[1.0629, 1.5619, 0.9476, 0.5760],
        [1.0692, 0.6981, 1.0153, 0.7072],
        [0.8134, 0.9905, 0.5658, 0.4600],
        [0.7987, 1.1546, 1.5364, 0.4705]])

In [53]:
x@y

tensor([[1.0629, 1.5619, 0.9476, 0.5760],
        [1.0692, 0.6981, 1.0153, 0.7072],
        [0.8134, 0.9905, 0.5658, 0.4600],
        [0.7987, 1.1546, 1.5364, 0.4705]])

In [59]:
x=torch.randn(2,2)
z=torch.cat([x,x],axis=1)

In [60]:
x.shape,z.shape

(torch.Size([2, 2]), torch.Size([2, 4]))

In [61]:
x,z

(tensor([[ 0.0423,  1.0060],
         [ 1.1726, -0.1200]]),
 tensor([[ 0.0423,  1.0060,  0.0423,  1.0060],
         [ 1.1726, -0.1200,  1.1726, -0.1200]]))

In [63]:
x=torch.arange(25)

In [73]:
x=x.reshape(5,5)
x[3,2]=33

In [74]:
x.max()

tensor(33)

In [76]:
val,idx=x.max(dim=0)
val,idx

(tensor([20, 21, 33, 23, 24]), tensor([4, 4, 3, 4, 4]))

In [77]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 33, 18, 19],
        [20, 21, 22, 23, 24]])

In [79]:
import torch

x=torch.tensor([[1.,2],[3,4]],requires_grad=True)
print(x)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [83]:
y=x.pow(2).sum()

In [84]:
y.backward()
x.grad

tensor([[2., 4.],
        [6., 8.]])

In [1]:
import torch

In [2]:
x=torch.tensor([[1.,2.],[9.,4.]],requires_grad=True)
x

tensor([[1., 2.],
        [9., 4.]], requires_grad=True)

In [3]:
y=x.pow(2).sum()

In [4]:
y

tensor(102., grad_fn=<SumBackward0>)

In [5]:
y.backward()

In [6]:
x.grad

tensor([[ 2.,  4.],
        [18.,  8.]])

In [7]:
z=y.pow(3)

In [8]:
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [16]:
a=torch.rand(500,6400)
b=torch.rand(6400,200)
%timeit z=x@y
z

7.49 ms ± 599 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


tensor(1061208., grad_fn=<PowBackward0>)

In [17]:
import numpy as np
x=np.random.random((500,6400))
y=np.random.random((6400,200))
%timeit z=np.matmul(x,y)
z

10.5 ms ± 751 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


tensor(1061208., grad_fn=<PowBackward0>)

In [18]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'


In [19]:
device

'cpu'

In [20]:
a=a.to(device)
b=b.to(device)


In [21]:
a=a.cpu()